### PR TITLE
Add json representation of site to each page for fulltext search and other uses

### PR DESCRIPTION
**Pull request by dmgig**
Hi - sorry for the new pull request instead of building on the other, but I think I addressed all of your issues. Hopefully this works better for you. Feel free to close the other one and comment on this one if you'd like more changes. 

Thanks for having a look and for the feedback, it was very helpful.

Dave

### CODE REVIEW

**Comment by joakin** [comment]
Hey, nice! I’ll have a deeper look into this soon, but it looks good first sight!

**Comment by joakin** [comment]
Hey @dmgig I've downloaded your PR and done amends in #17 if you want to have a look. I will merge and release a new version as soon as CI passes.

In the end I think it is best if this tool generates a JSON file in the output folder, without changing its contents.

You can then fetch the JSON file with JS, and process them stripping the tags if that is what you want to do.

I'll let you know when I release, and when you can check the docs. Let me know if this works for you, AFAICT it should be good enough 😄

**Comment by joakin** [comment]
Version 1.8.0 has been released. Check and see if that works for you. Open an issue if you can't figure out how to make use of the JSON file and I'll try to help.

The docs for the new feature you started are here: https://github.com/joakin/markdown-folder-to-html#site-contents-and-information-for-custom-templates

And this is an example of the JSON file it generates: https://chimeces.com/markdown-folder-to-html/contents.json

Maybe for your use case you should use the markdown itself instead of the HTML for the search indexing 👍

**Comment by joakin** [comment]
BTW if you get search to work and have a OSS public template that does it I'd love to link to it from the README 😃

**Comment by dmgig** [comment]
Hey that's great! It looks good, I'll set it up with a search template and make a repo for one. Thanks again!

**Pull request merged**
